mybatis-plus:
  configuration:
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: humaoyang123..
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlineeducationplatform?serverTimezone=GMT%2B8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    hiddenmethod:
      filter:
        enabled: true