mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: humaoyang123..
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlineeducationplatform?serverTimezone=GMT%2B8
  redis:
    host: 192.168.43.131
    port: 6379
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-ucenter
  profiles:
    active: dev
feign.hystrix.enabled: true
server:
  port: 8160
wx:
  open:
    appId: wxed9954c01bb89b47
    appSecret: a7482517235173ddb4083788de60b90e
    redirectUrl: http://localhost:8160/api/ucenter/wx/callback